### ISSUE TITLE
netzwerkswitch im weltenbaulabor installieren

### ISSUE THREAD

**Issue by cmile** [c-base/meta#102]
am besten mit permanenter stromversorgung...
ggf. wäre es sinnvoll, wenn jemand einen VLAN-fähigen switch verbauen würde und dort crew- und alien-netz verfügbar wären

**Comment by ghost** [comment]
@c-MM hat switches bestellt, die VLAN-fähig sind. Bitte darauf warten.

**Comment by cascha42** [comment]
now installed together with a aruba ap near the library by @uwekamper and me.
Closing.
