### ISSUE TITLE
Bürostuhl für Nerdarea motorisieren

### ISSUE THREAD

**Issue by uwekamper** [c-base/meta#112]

**Comment by jaseg** [comment]
To avoid machine uprising and protect the interests of humanity, this project has been cancelled.

**Comment by cmile** [comment]
denied :)

**Comment by uwekamper** [comment]
Wie wäre es mit einem Kettenantrieb?

**Comment by uwekamper** [comment]
So mit links und rechts nen Hebel an der Armlehne

**Comment by berlincount** [comment]
Bitte nicht. Der Estrich im Keller ist durch die Bank schwer beschädigt; ohne diesen zu reparieren ist eigentlich schon die Situation auf der Brücce und im c-lab untragbar. (Im Soundlab liegen IIRC Matten aus),

**Comment by uwekamper** [comment]
Mit Gummi-Ketten wäre das sogar bodenschonender als die bisherigen Stühle mit den harten Rollen.

**Comment by berlincount** [comment]
I want numbers. Bitte Reibungskoeffizienten raussuchen. Ich halte die Rollreibung der Gummikette durch größere Kontaktfläche für weniger bodenschonend, und würde vorab widerlegt werden wollen.

**Comment by uwekamper** [comment]
Inspiration: Lumag D-350 Raupendumper

![](http://i.ebayimg.com/t/Lumag-MD-350-Raupendumper-Kettendumper-Motorschubkarre-Dumper-Transporter-/00/s/MTAwMFgxMDAw/z/JJEAAOSwd3dXFyLV/$_57.JPG)
http://www.ebay.de/itm/261851298605

**Comment by kihaki** [comment]
+1

**Comment by cmile** [comment]
ich seh schon, das wird wohl nix :(
