### ISSUE TITLE
zweiter Barstatusindikator Nerdarea

### ISSUE THREAD

**Issue by ij0n** [c-base/meta#113]
der Barstatusindikator in der Nerdarea ist leider aus mehreren Ecken nicht ablesbar. Wir benötigen daher einen zweiten, damit von allen sitzplätzen (durch wenden des kopfes) ein barstatusindikator erkennbar ist.

**Comment by jaseg** [comment]
Wir haben gestern beim Aufräumen etwa 70% eines weiteren Barstatusindikators (Frontplatte und Seitenplatten) gefunden. LED-Streifen können gern aus der mit "OpenStep" beschrifteten Kiste links genommen werden. Es fehlt dann noch eine Rückplatte und Plotterkrams für vorne drauf. Zur Ansteuerung würde ich den tatsächlich einfach parallell zu dem bestehenden schalten.
