### ISSUE TITLE
Sonnenschirmleichen als Deko für draußen nutzen

### ISSUE THREAD

**Issue by uwekamper** [c-base/meta#114]

**Comment by ij0n** [comment]
Alternative: Sonnenschirmleichen "strippen", also aller Stoff entfernen und das verbleibende Gestänge mit wasserfesten RGB-LED-Stripes dekorieren. Damit können wir auf dem Camp aber auch ansonsten unseren Uferstreifen verschönern.

**Comment by jaseg** [comment]
Liegen IIRC derzeit unterm Matelight

**Comment by uwekamper** [comment]
Unter dem Matelight liegen zwei komplett neue Schirme. Der alte Schirm steht draußen.

**Comment by uwekamper** [comment]
Alte Schirme waren viel zu alt und ekelig - alle entsorgt!
