### ISSUE TITLE
Luftabsaugung in der Werkstatt installieren

### ISSUE THREAD

**Issue by ij0n** [c-base/meta#116]
Wir hätten gerne eine elektrische Maschine die die Werkstatt entlüftet. Z.b. wenn jemand mit Farbe rumgespielt hat, oder mit Lösungsmitteln, Epoxy, Feinstaub-erzeugenden Werkzeugen usw usf.

Ein Lüfter der Luft aus der Werkstatt raussaugt (und aus dem Kellerfenster ausstösst) ist die Lösung dafür.

Fancy wirds mit zeitgesteuertem Schütz, der bei einem Knopfdruck das Werkstatt-Luftvolumen zweimal raussaugt und danach den Lüfter wieder ausmacht.

Lüfter müsste es noch geben, liegt laut buschi im coundlab. Der is soweit ich weiss für das soundlab extrem überdimensioniert.

Achtung: Dies ist eine andere Anlage als https://github.com/c-base/meta/issues/117, die Späne aus den Maschinen saugt und diese aus dem Luftstrom herausfiltert und die gefilterte Luft wieder in die Werkstatt speist.

**Comment by ij0n** [comment]
Nein, diese Abhängigkeit würde ich nicht eingehen wollen. Die Luftabsaugung aus dem zukünftigen Maschinenraum muss Richtung Weltenbaulab oder Richtung Flur erfolgen, um Brandschutzwände nicht penetrieren zu müssen.

Die Luftabsaugung aus der Werkstatt soll direkt aus der Werkstatt in den Hof gehen. Wenn man da den Maschinenraum mit anklemmen wollen würde, müsste man sowohl die Brandschutzwand zwischen Werkstatt und Nerdarea, als auch die Brandschutzwand zwischen Robolab und Maschinenraum penetrieren. Dabei entstehen (wenn man das Vorschriftsgemäß machen lässt) deutlich höhere Kosten, als einfach ein zweiter Radiallüfter mit nen paar Rohren.

**Comment by buschmann** [comment]
jeder raum sein eigener abzug!

**Comment by uwekamper** [comment]
@ij0n hat vorgeschlagen: Das Glas aus einem der Kellerfenster entfernen und durch etwas mit Loch ersetzen, in das man dann die Lüfter einsetzen kann.

**Comment by buschmann** [comment]
nun ja so was in der art schlug ich ja auch schon vor 15 jahren vor ;))
und irgendwo muss noch ne eigentlich "neue" lüfterbox parken.. macht
ordentlich liter...
ich komme morgen mal rum so nachmittags die kühle bude vollstinkern ..hehe

Am So., 19. Juni 2022 um 00:37 Uhr schrieb Uwe Kamper <
***@***.***>:

**Comment by ij0n** [comment]
Erledigt.
