### ISSUE TITLE
Späneabsaugung in der Werkstatt installieren

### ISSUE THREAD

**Issue by ij0n** [c-base/meta#117]
Zur Installation der Tischkreissäge und rund um die Dauerleihgabe der Flottjet-Maschinen gab es mit dem circle die Absprache, dass, bevor diese in Betrieb genommen werden, eine Späneabsauganlage installiert werden soll.

Die Planung der Späneabsauganlage führe ich diese Tage durch, auf dem Circle am 14.05.2015 werde ich die notwendigen Mittel beantragen.

Achtung: Die Späneabsauganlage saugt Luft aus der Werkstatt durch die Maschinen und bläst diese Luft durch einen Filter in die Werkstatt, ohne die Späne und den Staub. Dies ist eine andere Anlage als die Luftabsaugung (https://github.com/c-base/meta/issues/116), die tatsächlich der Entlüftung dienen soll.

Anlagen, bei denen die gefilterte Abluft aus einem Schlauch oder Rohr kommt, so dass man diese theoretisch direkt aus dem Fenster raus schieben könnte sind disproportional so viel teurer, dass wir besser zwei günstigere anlagen installieren, also einmal "Späne filtern und Restluft wieder in den Raum blasen" und einmal "Luft mit Feinstaub und Gestankpartikel raussaugen"

**Comment by buschmann** [comment]
...saugt verschmutzte luft durch einen filter.
nicht die dreckige luft durch die motoren ziehen und dann in filter blasen wie oben steht ! :()

**Comment by ij0n** [comment]
Der Gesamtpreis für die erste Ausbaustufe mit manuellem Schalten der Komponenten und Schieber (ohne automatik) ist 283,39€

Die Preisaufstellung für die Einzelkomponenten findet sich hier: https://docs.google.com/spreadsheets/d/1MkgroHkoNsiWYG-OTQj5_TszlPoq5upsG-7QK9re2ow/edit?usp=sharing

**Comment by ij0n** [comment]
\begin{table}[h]
\begin{tabular}{llllll}
                                & L채nge St체ck & Stck & Stckpreis & Gesamtpreis & Shoplink / Firma                                                                                                                                                              \\
HT Rohr DN100mm                 & 2000        & 2    & 5.15      & 10.3        & Bauhaus Prod.Nr. 13624768                                                                                                                                                     \\
HT Rohr DN100mm                 & 1000        & 6    & 3.1       & 18.6        & Bauhaus Prod.Nr. 13624689                                                                                                                                                     \\
HT Rohr 110 Abzweig 87째         &             & 5    & 4.05      & 20.25       & Bauhaus Prod.Nr. 13625365                                                                                                                                                     \\
HT Bogen DN110 87째              &             & 6    & 1.29      & 7.74        & Bauhaus Prod.Nr. 13625035                                                                                                                                                     \\
Absperrschieber                 & 10          & 3    & 16.07     & 48.21       & http://www.amazon.de/Absperrschieber-100-Zubeh\%C3\%B6r-f\%C3\%BCr-Absauganlage/dp/B002R69KZG/ref=pd\_rhf\_se\_p\_img\_7                                                      \\
Flexschlauch                    & 5000        & 1    & 37.9      & 37.9        & http://www.amazon.de/Absaugschlauch-PU-transparent-100-Absauganlage/dp/B002R675PS/ref=pd\_sim\_60\_2?ie=UTF8\&refRID=0RBNCENJ8KFCPJAT6M8Y                                     \\
Schlauchschellen                &             & 1    & 6.49      & 6.49        & http://www.amazon.de/Schlauchschellen-Edelstahl-Bandbreite-100-120-rostfrei/dp/B00PHC4SPE/ref=pd\_cp\_60\_3                                                                   \\
Absauganlage "Zipper Zi asa550" &             & 1    & 136.9     & 136.9       & http://www.amazon.de/Zipper-ZIPPER-Absauganlage-\%C2\%BBZI-ASA550\%C2\%AB/dp/B008GTJJLI/ref=sr\_1\_10?s=diy\&ie=UTF8\&qid=1431365785\&sr=1-10\&keywords=sp\%C3\%A4neabsaugung \\
Rohrabschlussdeckel             &             & 4    & 1.05      & 4.2         & bauhaus Prod.Nr. 13625530                                                                                                                                                     \\
                                &             &      &           &             &                                                                                                                                                                               \\
                                &             &      & SUMME     & 286.39      &                                                                                                                                                                              
\end{tabular}
\end{table}

**Comment by ij0n** [comment]
Der circle hat die Kosten für dieses Projekt bewilligt. Die Produkte vom Baumarkt sind (dank uk) bereits an Bord. Der Rest von Amazon ist bestellt und sollte in der Woche vom 18. bis 22. ankommen.

**Comment by ij0n** [comment]
3 von 4 Paketen sind bereits angekommen und heute wurde der "Backbone" in der Werkstatt installiert. In den nächsten Wochen werden Stück für Stück alle Maschinen dort angeschlossen. Morgen oder übermorgen sollte die Absauganlage selbst ankommen.

**Comment by ij0n** [comment]
4 von 4 Paketen wurden geliefert. Der Kopf des c-lurpc wird heute an Bord gebracht, entweder durch Carsharing oder durch nen Taxi.

**Comment by ij0n** [comment]
remaining tasks:

  * kupferdraht einbringen und die gesamte anlage erden
  * ctromvercabelung für den centralc-lurpc rendern

**Comment by ij0n** [comment]
![explosionszeichnung](https://cloud.githubusercontent.com/assets/4204566/15511996/1774cc74-21de-11e6-881d-e7460aead394.jpg)

Form bauen für tiefgezogene automatische Saugluftschieber.

**Comment by ij0n** [comment]
wir haben einen anderen modus gefunden und schieben die absaugung dahin wo wir sie brauche. die rohre sind zu dünn und die biegeradien der rohre zu klein und das system ist falsch konzeptioniert. *fail*.
