### ISSUE TITLE
Links in Welcome-Mail für Neumember korrigieren

### ISSUE THREAD

**Issue by ij0n** [c-base/meta#118]
Ein neumember trug mir zu, dass der link in der welcome-mail auf das coredump-cimp zeigt. der coredump als wiki wurde abgelöst durch ein Dokuwiki

Dort ist die aktuelle Version des CIMP. Der korrekte Link ist daher: https://wiki.c-base.org/dokuwiki/cimp

**Comment by uwekamper** [comment]
email wurde schon vor längere Zeit angepasst.
