### ISSUE TITLE
Elektronisches Schloss für Soundlab

### ISSUE THREAD

**Issue by uwekamper** [c-base/meta#119]
Ich habe mit Jaseg und Xen heute eine Schaltung gebaut, mit der das Soundlab per LDAP+PIN aufgeschlossen werden kann.

Siehe auch Seminarraum (#120)

**Comment by uwekamper** [comment]
@jaseg Der MOSFET wird bei Dauerschaltung an 12V, 1A noch sehr warm. Kannst du dir bitte meine Schaltung nochmal anschauen, ob da noch was kaputt ist?

**Comment by uwekamper** [comment]
@ri0t Wir benötigen noch ein Loch in der Wand beim Soundlab für ein Twisted-Pair-Kabel (das Keypad hat einen RJ45-Anschluss). Außerdem brauchen wir noch ein Gehäuse für das Keypad (Lasercutten!) und ein Gehäuse für den Raspberry-Pi. Der Raspberry-Pi ist von mir (spende ich). Die SD-Karte ist **geliehen** von Saces.

**Comment by jaseg** [comment]
@uwekamper Da ist höchstwahrscheinlich nix kaputt, der mosfet ist nur nicht besonders gut. Schraub halt nen Kühlkörper dran. Ich hab hier aber grad noch 'ne Tüte IRLZ34N-Logic level-MOSFETs gefunden, die können das auch ohne Kühlkörper direkt aus nem Mikrocontroller-IO. Ich bring die heute Abend mal mit.

**Comment by ij0n** [comment]
der xen könnte das gehäuse ausdrucken. designed habe ich das gehäuse für das keypad schon - an der c-labtür ist es angebracht.

**Comment by XenGi** [comment]
gebt mir ein stl, ich drucks.

**Comment by uwekamper** [comment]
Ich hab heute die Türfalle zerstört. Muss neue besorgen. EffEff 17(R) --- D11

Evtl. will man aber doch lieber was kaufen, was Dauerstrom abkann.

**Comment by berlincount** [comment]
haa-haa .. *hust* .. okay .. ich werd dienstag mal Olsen (unser Schlossmensch) kontakten wegen der anderen Sachen, vielleicht kann der einfach mitbestellen.

**Comment by uwekamper** [comment]
Ich hab gestern die elektrische Türfalle ("Summer") kaputt gemacht.

**Comment by uwekamper** [comment]
@berlincount Hast du bereits mit Olsen gesprochen? Oder soll ich mich selbst um einen Ersatz für die Türfalle kümmern?

**Comment by ri0t** [comment]
Ding is wieder am rennen und schön montiert.

Danke an alle Beteiligten!
