### ISSUE TITLE
Mal Widerstände für's c-lab nachbestellen

### ISSUE THREAD

**Issue by jaseg** [c-base/meta#121]
http://www.aliexpress.com/item/Carbon-film-resistor-assorted-kit-0-33-ohm-4-7M-ohm-1-4w-5-tolerance-commonly/1865588663.html

**Comment by ij0n** [comment]
wiederstand ist zwecklos.

**Comment by uwekamper** [comment]
Außerdem: Lüsterklemmen (die kleineren)
Schraubterminals zu Anlöten.

**Comment by jaseg** [comment]
Wird das hier jetzt ein generisches c-lab-einkaufsissue? Von mir aus ;)

Schraubterminals gibts günstig bei [TME](https://tme.pl). Da gibts auch die unglaublich praktische kodierbare Steckvariante (Schraubterminal, das direkt in eine spezielle Buchse gesteckt wird).

**Comment by jaseg** [comment]
http://www.aliexpress.com/store/product/Free-Shipping-31valuesX20pcs-620pcs-Monolithic-Multi-layer-Ceramic-Capacitor-Assortment-Kit-10PF-680NF-MLCC-Pack/503693_1364641855.html
http://www.aliexpress.com/item/1-4w-0-25w-122-kind-50-pcs-6100-pcs-0-3ohm-1m-1-metal-film/32259889710.html
http://www.aliexpress.com/item/1-4W-Metal-Film-Resistor-Kit-Resistor-Pack-1-tolerance-150valuesX50pcs-7500pcs/723485498.html
http://www.aliexpress.com/item/Free-Shipping-1-4W-Metal-Film-Resistor-Assorted-Kit-0-25W-1-Ohm-10M-Ohm-1/1720341601.html
http://www.aliexpress.com/item/1-4W-Metal-Film-Resistor-Samples-kit-100-kindsX50pcs-5000pcs/32312235409.html

**Comment by uwekamper** [comment]
Widerstände sind da und sind einsortiert.
