### ISSUE TITLE
Leuchtmittel für die Latüchten des Soundlabs besorgen

### ISSUE THREAD

**Issue by ri0t** [c-base/meta#123]
Wir brauchen 14 E14 leuchtmittel, das sind die kleenen Schraubanschlüsse.
Idealerweise haben die LED, sind nicht alle in der gleichen Leuchtfarbe/Leistung.
Cash hat bestätigt, das wir den Betrag unabhängig vom Soundlab budget ausgeben können, da Verbrauchsmittel.

**Comment by uwekamper** [comment]
@woodworker hat LED-Leuchtmittel gekauft und wir haben sie schon eingebaut.

**Comment by woodworker** [comment]
ist ja jetzt alles aufgebaut

**Comment by ri0t** [comment]
This issue was moved to c-base/soundlab#27
