### ISSUE TITLE
Mehrere Strommultiplexer werden benötigt

### ISSUE THREAD

**Issue by ri0t** [c-base/meta#128]

**Comment by ij0n** [comment]
Einen mehr kaufen für: https://github.com/c-base/meta/issues/91

**Comment by berlincount** [comment]
vielleicht gleich mal was ordentliches, vernünftig montierbares kaufen?

http://www.kopp.eu/de/produktkatalog/steckdosenleisten-verlaengerungen-und-adapter/steckdosenleisten-unoversal

gibts auch in schlagfest: http://www.kopp.eu/de/produktkatalog/steckdosenleisten-verlaengerungen-und-adapter/steckdosenleisten-powerversal

**Comment by woodworker** [comment]
ich hab mal eine 10er abgeladen
und aus dem escapepod haben wir noch einige geholt

wir sollten schauen ob das reicht und das issue schließen

**Comment by ri0t** [comment]
Reicht erstmal, ich würde das aber wg. #142  und #144 nochmal wiederkäuen wollen ;) :neckbeard:

**Comment by ri0t** [comment]
This issue was moved to c-base/soundlab#26
