### ISSUE TITLE
A (soundlab) nonpublic wiki

### ISSUE THREAD

**Issue by woodworker** [c-base/meta#129]
We the soundlab members need a wiki for information exchange
As this wiki contains a list of available gear in the soundlab
i would prefer this to be non public/members only/(maybe even soundlab members only??)

Maybe the c-lab is also interested in a members only wiki

**Comment by XenGi** [comment]
Another dokuwiki with login based on ldap group and auth required? Sure why not.
Where do we host it? External or internal? The c-lab wiki could be hosted on colophonia.

**Comment by woodworker** [comment]
would like to have this available from everywhere
https + ldap auth

**Comment by cketti** [comment]
I believe the current wiki already supports areas with access limited to specific LDAP groups. No need to host yet another service.

**Comment by berlincount** [comment]
I'm opposed to limiting non-critical documentation towards other members, i.e. every member should be able to read every internal Wiki (excluding Bruecce + Ceymaster). I'd be fine if writing was limited to the owner's LDAP group.

**Comment by cmile** [comment]
@cketti is right, https://wiki.c-base.org supports LDAP based ACLs. 
i can limit write access for "soundlab" or any subtree to cey-soundlab, if that is OK?

please do not set up another wiki.

**Comment by ri0t** [comment]
can we have an internal corner as subtree from soundlab? like soundlab-internal or soundlab/internal - dunno what makes sense.. I'm preparing the available gear list in libreoffice calc this evening. Among others, for QR printing.

**Comment by cmile** [comment]
The namespace soundlab:internal is now only accessible for the ldap group cey-soundlab

https://wiki.c-base.org/dokuwiki/soundlab:internal:start

**Comment by ri0t** [comment]
This issue was moved to c-base/soundlab#28
