### ISSUE TITLE
Hackanoon/Crew-Nachmittag

### ISSUE THREAD

**Issue by uwekamper** [c-base/meta#13]
Leute einladen, an c-base-fnord frickeln. Aber halt nicht 24h, weil dann sind wir alle fertig, sondern eher so "'n Nachmittag". 
So Samstagnachmittag z.B. Optional nachher Biertrinken.
Können wir machen, sollten wir aber erstmal die LEDs und foo anfängerfreundlich aufbereiten, sodass $Noobs damit auch basteln können.

**Comment by jaseg** [comment]
bump

**Comment by XenGi** [comment]
Plöng! Gibts da noch interesse dran oder kann das weg?

**Comment by bronsen** [comment]
Ich sage: bei Bedarf ein neues Issue aufmachen.
