### ISSUE TITLE
Namen finden für Projekt "Späneabsaugung"

### ISSUE THREAD

**Issue by ij0n** [c-base/meta#130]
Es handelt sich um dieses Projekt: https://github.com/c-base/meta/issues/117

Namensvorschläge:

Späneabsaugung
Schlurps
Zentralschlurps
Lutschung
Zentrale Lutschung
Staublunge

Bitte weitere Namensvorschläge kommentieren.

**Comment by jaseg** [comment]
Ich bin für Schlurps. Lutschung klingt irgendwie komisch...

**Comment by woodworker** [comment]
Schlurps++

**Comment by berlincount** [comment]
Sucky :D

**Comment by ij0n** [comment]
Schlurps oder Zentralschlurps.
c-lang: c-lurps oder centralc-lurps

so sei es! closed.

**Comment by XenGi** [comment]
Also ich und amphibious haben uns gerade auf deep throat geeinigt.
