### ISSUE TITLE
Barbot-Hubelthon veranstalten

### ISSUE THREAD

**Issue by uwekamper** [c-base/meta#131]

**Comment by XenGi** [comment]
Was ist denn ein Hubelthon? Ein Hackathon wo keiner nen Laptop oder Lötkolben dabei hat?

**Comment by cmile** [comment]
keiner hat selten nen laptop dabei, der nutzt meist sein mobiltelefon

hackathon -> hacking-marathon
hubelthon -> hubeling-marathon

ziel ist es ideen zu sammeln, wie der barbot-dienst verbessert, erleichtert, beschleunigt oder einfach attraktiver gemacht werden könnte
