### ISSUE TITLE
Neues Oszi mit ner festen IP (10.0.1.x) versehen und in die Map of Interfaces eintragen

### ISSUE THREAD

**Issue by ij0n** [c-base/meta#132]
Das neue Oszi hat nicht nur nen Ethernetport, sondern angebl auch ein Webinterface.

Jemand müsste mal bei den admaxen
  * eine feste IP und NAmensauflösung beantragen
  * das Webinterface in der Map of Interfaces eintragen (https://github.com/c-base/c-base-map)

**Comment by jaseg** [comment]
Dieses Gerät ist *das letzte*, was wir am Netz haben wollen.

**Comment by ij0n** [comment]
@jaseg Mit welcher Begründung?

**Comment by jaseg** [comment]
Ranzige Chinasoftware auf einem Gerät, dem Internetanbindung exakt *keinen* Mehrwert bringt.

**Comment by jaseg** [comment]
(lies: aus Sicherheitsgründen)

**Comment by ri0t** [comment]
Wozu ist das da drauf? Ich habs mir mit coon angesehen und es sah nicht aus, als hätte es IRGENDein feature...?!

**Comment by coon42** [comment]
Man kann sich den Displayinhalt remote anzeigen lassen. Irgendwie gibts da noch ne art API, über die man ggf. mehr machen kann. Am Internet will ich das Ding gar nicht haben. Crewlan only würde vollkommen reichen.

**Comment by berlincount** [comment]
d.h. DHCP ohne Default Route?

**Comment by coon42** [comment]
jop, irgendwie sowas
