### ISSUE TITLE
c-fefe css-theme erzeugen

### ISSUE THREAD

**Issue by ij0n** [c-base/meta#134]
jemand müsste mal ein c-fefe css-theme erzeugen, dass fefe-artikel im raumstationslook anzeigt. damit wir das auf den vielen monitoren hier überall anzeigen können.

**Comment by cketti** [comment]
Und demnächst legen wir dann noch die BILD aus? Gegen Fefe auf Stationshardware!

**Comment by XenGi** [comment]
Also an de mcss theme bin ich definitiv interessiert aber auf unseren Monitoren will ich da auch nicht haben. Fefe lesen macht unglücklich.
