### ISSUE TITLE
c-gate reparieren

### ISSUE THREAD

**Issue by ij0n** [c-base/meta#138]
das c-gate muss instand gesetzt werden, das heisst: zerlegen, anschauen, durchchecken. das mittlere teil muss aufgearbeitet werden, wasserfestigkeit fehlt auch und ganz viel beleuchtung usw.

brain kennt sich mit der struktur aus und hat das ding mehrfach auseinandergebaut und wieder zusammgenbaut.

wir wollen das ding zum camp mitnehmen.

**Comment by cmile** [comment]
camp is vorbei, das gate wurde teilweise restauriert, aber es bedarf noch weiteren make-ups, deswegen bleibt der hubel offen.

**Comment by ij0n** [comment]
Was bleibt denn noch offen? Welche Tätigkeiten müssen gemacht werden? Ich denke es ist besser die notwendigen tätigkeiten auf zwei oder drei kleinere hubel aufzusplitten.

**Comment by cb-miramar** [comment]
das cgate brauch an einigen stellen einen neuen anstrich, einige stellen müssen ausgebessert werden,  und die bleche sollten mit breite plosternägeln besser befestigt werden

**Comment by ghost** [comment]
das c-gate muss zerlegt werden - platzbedarf mit anderen teams absprehcen! 

nach dem zerlegen muss gespachtelt und geschliffen und neu gemalt werden. der regenschutz muss entfernt werden und das licht und der lüfter müssen wieder instand gesetzt werden.

**Comment by ij0n** [comment]
das c-gate soll am (ersten) sonntag zerlegt werden. e-punc hat nen plan und kümmert sich, braucht aber hilfe!

**Comment by uwekamper** [comment]
Akendo und ich haben:

- Alte verstaube Lüfter entfernt
- Service-Hatch installiert für leichteren Zugang zu den wichtigen Bereichen des c-gates, wenn es wieder aufgebaut ist.

- e-punc hat:

- Lose Metallplatten festgeschraubt
- Orange Teile abgeschliffen und neu gestrichen.

**Comment by ghost** [comment]
neue Lampen wurden eingebaut. Der Lüfter dreht wieder, und innen wurde blau gestrichen. aus gründen.
