### ISSUE TITLE
Lastregale im Escapepod leer räumen

### ISSUE THREAD

**Issue by ij0n** [c-base/meta#139]
Wir brauchen mehrere vernünftige Regale auf dem Camp um unsere Lebensmittel lagern zu können. Da der escapepod sowieso gerade im soundlab einzieht, bittet die c-base village orga, mindestens zwei Regale priorisiert leer zu räumen (inhalt rüber ins soundlab) , so dass diese mit aufs camp können.

**Comment by woodworker** [comment]
Das zeug ist gerade mal ein regal soundlab der rest ist "other"
und afaik sind die regale an die wand geschraubt

**Comment by ij0n** [comment]
dann lösen wir die Regale von der Vercshraubung und werfen noch ein bisschen "other" ins Soundlab, zumindest für die Dauer des Camps.
