### ISSUE TITLE
Regelmäßiger Löt-Abend im c-lab

### ISSUE THREAD

**Issue by uwekamper** [c-base/meta#14]
"Freies Gelöt"
"Betreutes Löten"
"Löten für Föten"

**Comment by jaseg** [comment]
Status? Das Issue wird bald ein Jahr alt. Wenn wir das nicht mehr brauchen oder wollen können wir das Issue auch zu machen.

**Comment by TeddyKopernikus** [comment]
Für große Löt-Events wäre es ggf. gut, mehr als einen Lötdampfabsauger zu haben.

Ansonsten klappte das spontane semi-betreute Löten kürzlich auch recht vortrefflich.

Eine größere Personenansammlung mit viel Parallelgelöt würde eher zu einer extremen Luftbelastung führen. Ein verteiltes Löten mehr Platz und Luftqualität für alle bedeutet, auch wenn darunter die Betreuungsquote pro Zeiteinheit geringer ist. Insofern spräche einiges gegen große Lötparties...

PS: Das Issue ist kürzlich 2 Jahre alt geworden. :)
