### ISSUE TITLE
HE1/Shuttle LED-Beleuchtungssteuerung

### ISSUE THREAD

**Issue by uwekamper** [c-base/meta#15]
USB-Buchse wie im Ingress-Tisch: http://www.reichelt.de/XLR-Einbaubuchsen-stecker/NEUTRIK-NAUSB-WB/3//index.html?ACTION=3&GROUPID=5188&ARTICLE=63206&SHOW=1&OFFSET=16&

**Comment by ij0n** [comment]
Was ist zu tun? Ist das nicht schon erledigt?

**Comment by coon42** [comment]
Funktionalitaet ist prinzipiell vorhanden nur der PI muesste neu aufgesetzt werden.
