### ISSUE TITLE
Spendenschlund knurren/schmatzen/rülpsen lassen

### ISSUE THREAD

**Issue by uwekamper** [c-base/meta#16]
Rasda nach der Nerd-Area-Tür fragen.

**Comment by ij0n** [comment]
was für holzbearbeitung denn notwendig? bitte vorsichtig damit umgehen oder mich fragen - ist von meshda handgeschnitzt das teil.

**Comment by XenGi** [comment]
Ich habe einen Aufbau mit einigen kleinen Sensoren die darin untergebracht werden müssen. Kann ich dir nächste Woche mal zeigen.

**Comment by ij0n** [comment]
gibt das dann auch ne info via mqtt dass jemand was gespendet hat?

**Comment by XenGi** [comment]
Ich benutz nen Teensy der hat erstmal kein Netzwerk aber an das Thing ein Internet zu schrauben sollte ein lößbares Problem sein.

**Comment by cascha42** [comment]
Wemos D1 (ESP8266) + IR-Lichtschranke + Soundmodul + kleiner Lautsprecher

**Comment by cascha42** [comment]
Nun ein Raspberry Pi 1 mit IR-Modul und Lautsprecher verbaut. Muss noch richtig eingestellt und programmiert werden.
Am Schlund nichts verändert, nur heißkleber.
