### ISSUE TITLE
Antenna Maintenance Day

### ISSUE THREAD

**Issue by XenGi** [c-base/meta#172]
Our antenna needs maintenance. We need to setup a crew of space exploration experts to do a regular checkup of the upper antenna section. Space suits are optional but at least some maintenance equipment would be good.

Maintenance crew:

  - XeN
  - coon
  - segfault
  - riot
  - count
  - ajuvo
  - nerdbeere
  - lux

**Comment by IGBC** [comment]
is there a scheduled date for maintainance yet?

**Comment by XenGi** [comment]
Not yet. We could setup a list for people to sign up. I think we need 20 to get a discount.

**Comment by IGBC** [comment]
some time in January is probably best.

**Comment by ri0t** [comment]
The weather should be crisp and clear to avoid safety issues and get a clear view. Also, count me in.

**Comment by XenGi** [comment]
I added a list for the maintenance crew. Just add a comment or ping me and I'll add you to the list.
cc @IGBC @ri0t @coon42

**Comment by ajuvo** [comment]
I'm in. @ajuvo

**Comment by luxferresum** [comment]
I'm in @XenGi

**Comment by ajuvo** [comment]
Did anyone identify proper windows of opportunity yet?
