### ISSUE TITLE
Ansteuerung für Plasma-Leitungen bauen

### ISSUE THREAD

**Issue by uwekamper** [c-base/meta#173]
Plasmaleitungen (aka "Spaceshlong") befinden sich im c-lab.

Evtl. ist sowas nützlich: http://www.watterott.com/de/EL-Sequencer

**Comment by ri0t** [comment]
Aus Diskussion mit @uwekamper: Es wird nichts weiter benötigt als eine drei (vier?)-kanalige FET-Steuerung die entsprechende EL-Netzteile (Inverter, i.d.R. 12V bei wenigen mA)  schalten kann. Wer auf oldschool steht, kann vermutlich auch (beleuchtete) Relais nehmen ;)

Damit das im Kreis blinkt, könnte man ein Schieberegister mit 555-Timer betreiben - oder mit nem ATTiny drei Pins im kreis laufen lassen.

Ich würds machen, aber immer wenn ich was mit FETs mache, tut das nachher nicht wie soll.

**Comment by coon42** [comment]
shlong issues zu einem zusammengefasst. Siehe: https://github.com/c-base/meta/issues/280
