### ISSUE TITLE
Build pageturning bookscanner

### ISSUE THREAD

**Issue by ij0n** [c-base/meta#174]
Vor einigen Jahren habe ich dieses Gerät gebaut: https://www.youtube.com/watch?v=65ViHOGyOv8

Es gab aber ein Problem - manchmal wurden mehrere seiten angesaugt (die seiten agierten wie eine membran). Deswegen hab ich aufgegeben.

Hiroshi hat sich von meiner Idee inspirieren lassen und hat dieses Gerät gebaut: http://www.diybookscanner.org/forum/viewtopic.php?p=18541

Hiroshi hat auch das Problem gehabt, dass manchmal mehrere Seiten angesaugt wurden, aber er hat eine Lösung gefunden - die Saugbox muss beim hochfahren auf halber Strecke stoppen, ein bisschen runterfahren und dann ganz zu Ende hochfahren - das biegt die Seiten ein bisschen und dann fallen mehrfach angesaugte Seiten ab. 

Hiroshis Scanner ist trotzdem noch relativ manuell, weil die Kameras nicht ausgelesen werden, sondern er nach dem scan die SD-Karten rausnehmen muss und die daten manuell kopieren. mit spreads haben wir aber bereits eine automatisierte Lösung für das auslösen der kameras, für das sortieren der bilder und für das übertragen der bilder auf den computer. 

wenn man jetzt hiroshis fortschritt und unseren spreads-fortschritt kombiniert, dann ist man wirklich an der stelle wo ich vor 5 jahren hinwollte - single button book scanning. buch einlegen, einen knopf drücken und fertigen scan mitnehmen für OCR oder so.

Sollte man also machen, braucht aber 
 größere umbauten oder neu schreiben von spreads (steuerung eines automatischen buchscanners kann spreads noch nicht) - und für so software krams brauchen wir ein oder zwei member, die sich hinsetzen und eine passende implementation schreiben die chdkptp (linux paket zum steuern der kameras) benutzt und die verschiedenen aktoren über z.b. arduino ansteuert.

**Comment by uwekamper** [comment]
Ist jetzt ein eigenes Projekt unter https://libreflip.org/
