### ISSUE TITLE
Right-justify von bildern im logbuch tut nicht

### ISSUE THREAD

**Issue by ri0t** [c-base/meta#183]
Hängt dann statt neben dem text, rechts überm text - eher doof.

**Comment by uwekamper** [comment]
Kannst du einen Post verlinken, bei dem das Problem auftaucht? Ich kann es nicht nachvollziehen.

**Comment by uwekamper** [comment]
Hier ist ein Beispiel: https://logbuch.c-base.org/archives/4922

Das Foto ist nun korrekt rechts umflossen dargestellt.

Es fehlten noch die Einträge für die Klasse ".alignright" im CSS.
