### ISSUE TITLE
Telegram-Bot für Matelight

### ISSUE THREAD

**Issue by uwekamper** [c-base/meta#185]

**Comment by cascha42** [comment]
ich versuche mich daran mal. hilfe ist erwünscht ;)

https://github.com/cascha42/matelight-telegram-bot/

cascha

**Comment by cascha42** [comment]
Der Bot ist soweit Fertig, und läuft nun unter dem Nutzernamen "@MatelightBot" auf Telegram.
Code: https://github.com/cascha42/matelight-telegram-bot

Danke an @uwekamper 

cascha
