### ISSUE TITLE
Bar streichen / Instand setzen / Reparieren

### ISSUE THREAD

**Issue by ij0n** [c-base/meta#193]
Kunststoffrohre tiefenreinigen
Hinter der Bar komplett neu streichen
Beleuchtung aktualisieren?? MQTT!

**Comment by ghost** [comment]
has been sanded - thx to xcds, needs painting - cillroy wants to paint this, so dont do it, unless you are cillroy

**Comment by ij0n** [comment]
bar has been sanded and painted! looks very nice now!
