### ISSUE TITLE
Holodeck in Stand setzen

### ISSUE THREAD

**Issue by ij0n** [c-base/meta#199]
mit selbst nachleuchtender giftgrüner Farbe die Fugen anmalen.

UV-Röhren erneuern/ergänzen

**Comment by ghost** [comment]
braucht noch gelbe uv-aktive neon nachleuchtfarbe

**Comment by uwekamper** [comment]
Herrenklos wurden gerade von einem Member und seinem Alien gereinigt

**Comment by ghost** [comment]
über ajuvo bestellte leuchtfarbe hat leider die falsche farbe und ist wahrscheinlich zu wenig
