### ISSUE TITLE
Lenovo Hydra zum Congress bauen

### ISSUE THREAD

**Issue by silbo** [c-base/meta#20]
XeN und coon

**Comment by jaseg** [comment]
Ein vierfach-Lenovo-Netzteil lässt sich nach einem Design aus der RFA für etwa 100€ basteln. Bislang haben wir das Geld nicht zusammenbekommen, deshalb kleb ich hier jetzt mal einfach "camp" dran. Vielleicht hilft's ja.

**Comment by cmile** [comment]
machen inzwischen fast alle USB-C
