### ISSUE TITLE
Memberkühlschrank in Putzlager einbauen

### ISSUE THREAD

**Issue by ij0n** [c-base/meta#200]
Der Memberkühlschrank braucht einen Platz. Vor dem Spiegel soll er nicht stehen.

Der Kühlschrank soll in den Profi-Putzschrank eingebaut werden, dort wo der Ausschnitt mit der Milchglasplatte ist. Er darf auch ein bisschen rausragen, das soll dann verkleidet werden.

**Comment by ij0n** [comment]
Abhängigkeit zu #190

**Comment by ghost** [comment]
wontfix
