### ISSUE TITLE
Catering für die Baucrew

### ISSUE THREAD

**Issue by ajuvo** [c-base/meta#226]
Nach Art eines ordentlichen Smuts an Seetagen in der c_ombu:se ein ewiges Fru:hstu:c sowie ein sta:ndiges Warmgericht bereithalten. 

z.B.:

Macronen
Sol_janca
Erbsensuppe mit Pfannkuchen mit Apfelmuc
Gru:ncol
... tbc

**Comment by ij0n** [comment]
sppoxe hat uns kartoffelsuppe gemacht
nerdbeere hat uns käse-lauch-suppe gemacht
nerdbeere hat uns auch noch eine kartoffelsuppe gekocht.

**Comment by ij0n** [comment]
spooxe und nerdbeere und alle die ewiges frühstück gekauft haben waren großartig!
