### ISSUE TITLE
Elektronik montieren für shlongs im Tiefgang

### ISSUE THREAD

**Issue by ij0n** [c-base/meta#227]
Die Spaceshlongs / Plasmatubes wurden im Tiefgang montiert. Sie benötigen Ansteuerelektronik.

Wir haben 8 Spaceshlongs mit jeweils 5 EL-Wires.

Wir brauchen also 40 getrennte EL-Wire Kanäle mit denen jeweils so ein EL-Wire-Inverter betrieben wird.

**Comment by coon42** [comment]
Wir brauchen also:

1 Microcontroller für alle 8 Schlongs:
  - Arduino Mega? Stm32? Node-MCU?
  - Entweder einen Raussuchen der mind. 40 IO pins hat, oder nen IO-Expander benutzen

1 Dicker Inverter fuer alle EL-Wires (http://bit.ly/2l4s4oH)
1 P6KE 400CA Überspannungsschutzdiode direkt an die Inverter Ausgangspins (http://bit.ly/2kI3sB9)
1 Koaxialkabel (Für Inverteranschlüsse gegen Störungen) (http://bit.ly/2l4xnV1)
8 Perfboards (http://bit.ly/2lpDPWh)
40 Optotriacs (http://bit.ly/2klJvfJ)
40 Triacs (http://bit.ly/2l5FdOW)
8 74HC595 Schieberegister (http://bit.ly/2lPlobC)
8 Schraubklemmen für Inverter (http://bit.ly/2lNMjX9)

- Je Leitung zum Inverter ein Koaxialkabel verwenden und die Schirme jeweils auf Ground legen
- 100KOhm an den Inverterausgang, damits nicht so wehtut, falls mal jemand dran fasst (ggf. widerstand reduzieren, bis es nicht mehr dunkler wird)
- Messen, wie viel Strom die EL-Wires ziehen. Falls die mehr ziehen, als die Optotriacs treiben können, müssen wir noch dickere Triacs dahinter schalten.



(Liste ggf. unvollstaendig. Genauere Informationen folgen)

**Comment by ri0t** [comment]
40 IO pins sind was viel. Mal über schieberegister oder andere demuxer nachgedacht?

**Comment by XenGi** [comment]
Seit ihr euch mit den 40 Pins sicher? Die Dinger haben doch jeweils nur 5 Strippen die ihr durch takten müsst. Das macht bei mir 5 Pins mit 5 Invertern. Ihr könnt die doch alle zusammen schalten.

- µC
  - GPIO 1 - Inverter 1
    - Schlong 1, Wire 1
    - Schlong 2, Wire 1
    - Schlong 3, Wire 1
    - [...]
  - GPIO 2 - Inverter 2
    - Schlong 1, Wire 2
    - Schlong 2, Wire 2
    - Schlong 3, Wire 2
    - [...]
  - GPIO 3 - Inverter 3
    - Schlong 1, Wire 3
    - Schlong 2, Wire 3
    - Schlong 3, Wire 3
    - [...]
  - GPIO 4 - Inverter 4
    - Schlong 1, Wire 4
    - Schlong 2, Wire 4
    - Schlong 3, Wire 4
    - [...]
  - GPIO 5 - Inverter 5
    - Schlong 1, Wire 5
    - Schlong 2, Wire 5
    - Schlong 3, Wire 5
    - [...]

Das ist dann nahezu unendlich erweiterbar.

**Comment by coon42** [comment]
Stimmt. Jetzt wo wir alles über Triacs machen, reicht ein Inverter pro Schlong. Theoretisch können wir sogar den Microcontroller einsparen und stattdessen Schieberegister und nen 555-Timer benutzen.

**Comment by ij0n** [comment]
jetzt seit ihr am kostenoptimieren, bevor das ding gebaut wurde?

http://www.ebay.de/itm/Arduino-Mega-2560-R3-Rev3-2012-Version-ATMEGA16U2-Board-Neu-Deutsche-Post-/222233082766?_trksid=p2141725.m3641.l6368

son mega kostet keine 15 eur und hat genug pins frei für jedes wire einzeln ansteuern. Und einzeln ansteuern ist geil, kann man geilere animationen machen.

ideen:
- ein spaceshlong geht richtung serverraum, wenn unsere website der c-base aufgerufen wird sagt unser webserver kurz bescheid und das ding blinkt für zwei sekuden
- der lange spaceshlong symbolisiert unseren uplink nach draussen, je schneller der blinkt, desto mehr daten ziehen wir gerade aus dem internet

deswegen besser nicht mit nur nem 555 und nem schieberegister machen, lieber im mikrocontrollerzoo schauen oder notfalls was kaufen.

**Comment by coon42** [comment]
Oder wir hängen da einen IO-Expander und ne Node-MCU dran

**Comment by XenGi** [comment]
Wenn mans so sieht. bin ich da auch für einzeln ansteuerbar. aber ich würde halt trotzdem versuchen redundante Teile zu vermeiden. Das schluckt nur unnötig Strom und erzeugt jede Menge Störungen.

Ein ESP Dingsi um die Schlongs ans MQTT zu hängen fänd ich auf jeden Fall ein must have!

**Comment by coon42** [comment]
Reicheltbestellung ist raus. Am Wochenende wird ein Prototyp gelötet worden sein.
