### ISSUE TITLE
Schleuse reinigen

### ISSUE THREAD

**Issue by ij0n** [c-base/meta#228]
Die Bleche in der Schleuse müssen gründlich abgeschruppt werden, damit die alle gleichmäßig sauber sind.

**Comment by ligi** [comment]
I could do this ( but have no permission to assign me to the task  here ) - know meccanically what to do I think - would need some info which chemiccals to use/avoid - would do this on the 14. - have time from then on and think it is also good to not do this task in the beginning of the building-week as some tasks might be dusty

**Comment by ghost** [comment]
We _think_, it might be Stahl, so Stahlreiniger (Kitchen supply) might work wonders. Test on a "unseen" spot first, perhaps? Or ask someone who knows or can "see" it.

**Comment by ij0n** [comment]
Cleaning agents and brushes have been bought. 

There is no dependency to ticket 231 or 241. Please just start doing this indepently of these tickets.

**Comment by ligi** [comment]
where can I find the cleaning agents and brushes?

but will do #231 before this cleaning task - still see this as a
dependency - always do cleaning after all dirty work is done ..

**Comment by uwekamper** [comment]
Hi @ligi! Ich habe die Bürsten in den Putzschrank gelegt. Wenn du zu den Toiletten gehst, direkt am Anfang des Ganges ist links eine Tür. Hinter der Tür ist ein Regal - da liegen Bürsten.

**Comment by ligi** [comment]
vielen Dank für die info!

**Comment by ligi** [comment]
Have to reterminate to tomorrow - also still unsure if it makes sense to do this task before all painting and stuff is done - I am a big fan of the DRY pattern not only in code but also in work like this ..-)

**Comment by ghost** [comment]
schleuse wurde mit lappen innen gereinigt. thx red.

**Comment by bengoshii** [comment]
Neu Bauwoche, neues Glück. Kann wiederholt werden.
