### ISSUE TITLE
Weltenbaulab tische anschleifen und streichen

### ISSUE THREAD

**Issue by ij0n** [c-base/meta#231]

**Comment by ij0n** [comment]
Im selben rutsch dann dem couchtisch nerdarea ablnschleifen und streichen

**Comment by ligi** [comment]
Das übernehm ich - müsste nur wissen:

 * welche farbe
 * sind inzwischen schleifgeräte auf station / wo ?
 * ab wann ist die station in der bauwoche tagsüber offen?

ich denk dieser task sollte vor #228 erfolgen

**Comment by ij0n** [comment]
Nein, es gibt hier keine Abhängigkeit zu #228

**Comment by ligi** [comment]
Ich könnte das gern heut machen - müsst nur wissen ab wann offen ist und wo ich schleifgerät und farbe/pinsel finde

**Comment by ghost** [comment]
abgeschliffen, 1. schicht ( eventuell sogar die finale laut comments ) mit hammerschlag appliziert - vorerst geschossen - reopen wenn 2. schicht notwendig

**Comment by ligi** [comment]
Can apply the second layer today but will be at an event before - so in base a bit later.
