### ISSUE TITLE
Shoppinglist

### ISSUE THREAD

**Issue by ghost** [c-base/meta#234]

**Comment by ghost** [comment]
uk braucht Schukostecker zum anschrauben

**Comment by ghost** [comment]
ego fragen welche und wieviele leuchtstoffröhren

**Comment by uwekamper** [comment]
Handbürsten

**Comment by uwekamper** [comment]
Leuchtmittel für 500 Watt Halogen-Baustrahler

**Comment by ij0n** [comment]
Fegespäne. Viel.

**Comment by ghost** [comment]
Schleifpapier für die am samstag auftauchenden maschinen

**Comment by ghost** [comment]
e27 fassung, am besten mit seitlicher montagemöglichkeit und (schwaches) leuchmittel - energiesparlampe

**Comment by ghost** [comment]
(Küchen)Stahlreiniger - u.a. für die Schleuse (Bitte _immer_ vorher das zu reinigende  Material prüfen - das Zeug is auf Grund der putzkörper sehr abrasiv)

**Comment by ghost** [comment]
4 Kartuschen mit transparentem Silikon für das Mosaik-Rahmen-Projekt

**Comment by uwekamper** [comment]
Destilliertes Wasser und Wasserbetten-Conditioner für das Wasser in der Blubberblasen-Säule

Für Project "Fix the Bubbler" #238

**Comment by ij0n** [comment]
Spachtelmasse für holz füllen

**Comment by ij0n** [comment]
Nagelschellen zum kabel befestigen für cven. 200-500 stck

**Comment by ghost** [comment]
all bought. done.
