### ISSUE TITLE
Fix the bubbler

### ISSUE THREAD

**Issue by ghost** [c-base/meta#238]
Bubbler doesn't bubble. Needs a wash and change of filters, light needs to be modernized

**Comment by ghost** [comment]
Tube is washed.

We found spare parts for the bubbler, so it works.

c-lab is rebuilding the lights

**Comment by uwekamper** [comment]
We should by conditioner fluid for waterbeds. Also we should use Aqua dest. instead of tap water. Tap water in Berlin has a lot of calcium in it - which causes ugly stains.

How many litres of water fit into the water column?

**Comment by ij0n** [comment]
10l aqua dest has been bought.

it still needs (controllable?) LEDs, and the bubbler has to be mounted

**Comment by bergie** [comment]
The capacity is 6l. Works!

![img_20170313_211854_643](https://cloud.githubusercontent.com/assets/3346/23873628/fbda2f4a-0832-11e7-9955-fdb2a404620e.jpg)
