### ISSUE TITLE
innenverkleidung fenster c_leuse

### ISSUE THREAD

**Issue by cmile** [c-base/meta#241]
zwei der bretter vom schaufenster hinter der c_leuse stehen rum.
die bemalung benötigt auch auffrischung.
wenn die bretter da weg und wiedr eingebaut sind, muss hinter der c_leuse gesaugt werden.

bitte vorsicht mit der sensiblen verkabelung der c_leuse...

**Comment by ligi** [comment]
I have the feeling this should be done before #228

**Comment by ij0n** [comment]
Nein, hier gibts keine Abhängigkeit. Die Innenverkleidung der Fenster haben nichts zu tun mit dem reinigen der Schleuse im öffentlich zugänglichen Bereich.

**Comment by Excds** [comment]
Me and Nerdbeere put it up.
