### ISSUE TITLE
Seltsame Tüte mit "Solarleuchten" bei Spinten

### ISSUE THREAD

**Issue by ghost** [c-base/meta#242]
What is it? How dare someone store such an ugly bag there..?

**Comment by ij0n** [comment]
is this still active or can it be closed?

**Comment by uwekamper** [comment]
Die steht immer noch da. Gehört afaik jolly, ist der noch Member?

**Comment by starpeak** [comment]
Wurde ins Hardwarelager bewegt und falls keine Besitzansprüche erklärt werden hätte evtl Toto Interesse an Verwendung. Hier wäre eine Klärung wünschenswert.
