### ISSUE TITLE
shoppinglist 2

### ISSUE THREAD

**Issue by ghost** [c-base/meta#247]
- [ ] Nutfräser, 8mm Schaft, 6mm Breite oder etwas schmaler. 1 oder 2 Klingen.
- [ ] Plastikrohre, 50mm Durchmesser, 3m Länge, insgesamt 36m: 36m, 50mm Kopos KC Tubes Reflective à 2 m, grau, 1550 KC
- [ ] Passende Klemmschellen für Plastikrohre: 50 x Klemmschelle M50 50mm anreihbar Clippschelle

- [x] sägeblätter für dekupiersäge - die mit querpin --> ist gekauft worden

**Comment by ghost** [comment]
gelbe nachleuchtfarbe uv-aktiv --> ist gekauft worden

**Comment by ghost** [comment]
Holzspachtel, nochmal 2kg. Das erste Kilo ist größtenteils von den runden tischen aufgesaugt worden --> ist gekauft worden.

**Comment by ajuvo** [comment]
ich kann montag, dienstag oder mittwoch mit meinem craftfahrceug einen einca:ufer und ceugs zum baumarkt und zuru:c c_auffieren. anforderung bitte per fon oder sms.

**Comment by ij0n** [comment]
Nutfräser, 8mm Schaft, 6mm Breite oder etwas schmaler. 1 oder 2 Klingen. 

Plastikrohre, 50mm Durchmesser, 3m Länge, insgesamt 36m

**Comment by uwekamper** [comment]
@ij0n brauchen für die Plastikrohre zusätzlich noch Halterungen oder haben wir die schon?

**Comment by ij0n** [comment]
@uwekamper weiss ich nicht. Ich denke die Halterungen brauchen wir auch, Details weiss cven.

**Comment by cven42** [comment]
moin
36m, 50mm Kopos KC Tubes Reflective à 2 m, grau, 1550 KC 
 und
 50 x Klemmschelle M50 50mm anreihbar Clippschelle

**Comment by berlincount** [comment]
https://www.amazon.de/gp/product/B00AUOI922/ = 25 Schellen = 12,99€ ; *2 = 25,98€ 
https://www.amazon.de/gp/product/B00A8HT9RU/ = 20m = 34,50€ ; *2 = 69€

94,98€ ;+4,10€ = 99,08€

**Comment by electronic-ego** [comment]
Schaut mal bitte online bei Würth ... M50 Leerrohr  und die Schellen  sind  dort evtl günstiger zu haben als über normal Handel bzw Amazon...

**Comment by berlincount** [comment]
https://www.elektromax24.de/3-m-fraenkische-fpku-em-f-50-mittleres-stangenrohr z.B. ist sogar schon netto teurer als Amazon ... Würth haben wir bisher kein Kundenkonto, Obeta-User hab ich grad den Support nach meinem Passwort gefragt ...

**Comment by cven42** [comment]
Baumarkt
mindestens 4 x M6 Eindrehgewinde (für Holz) und 4 x M6 Rackschrauben. 
wird gebraucht um die ATEM zu montieren --> _wurde besorgt_

**Comment by ij0n** [comment]
Ich denke mal @cven42  meint DIN 7985 PZ bzw ISO 7045
Also Linsenkopf, Pozidrive, M6-Gewinde
Länge so 60mm behauptet cven, finde ich aber unglaubwürdig!

**Comment by uwekamper** [comment]
@ij0n http://amzn.to/2na1zPv so sehen die aus. müssten aber eigentlich auch noch Schraubensätz im Soundlab sein. @ri0t müsste mehr wissen

**Comment by uwekamper** [comment]
Rackschrauben und Gewinde werden nicht mehr gebraucht. Wir haben gestern genug auf der Station noch vorrätig gehabt. ATEM wurde bereits testweise montiert.

**Comment by berlincount** [comment]
Obeta:
https://obeta.de/artikel/FRAE-FPKU-EMF-Rohr-grau-EN50/205738 = 3m = 6,47 €; *12 = 75,36€ (Mengenrabatt)
https://obeta.de/artikel/Frae-clipfix-50-Fra/E33987 = 25 Schellen = 16,23€ ; *2 = 32,64€ (nicht lieferbar)

107,82€ _netto_

https://obeta.de/artikel/ISO-Rohr-starr-50mm-3m-grau/V25991 / https://www.heinrich-haeusler.de/artikel/ISO-Rohr-starr-50mm-3m-grau/V25991 = 7x3m = 33,60€ ; *2 = 67,20€
https://obeta.de/artikel/Flexmuffe-zugfest-grau-50mm/V25999 / https://www.heinrich-haeusler.de/artikel/Flexmuffe-zugfest-grau-50mm/V25999 = 15 Schellen = 18,75€ ; *4 = 75,00€

142,20€ _netto_

Lieferung frei Haus.

Amazon trotzdem billiger.

**Comment by berlincount** [comment]
Estimated delivery: 18 Mar 2017 - 23 Mar 2017
