### ISSUE TITLE
find spot for trash pile, to be brought to BSR

### ISSUE THREAD

**Issue by ij0n** [c-base/meta#251]
find a spot for a BSR-Pile and put all the trash there. Also carry up the trash from under the left workbench in the workshop.

**Comment by ij0n** [comment]
carry trash up from workshop, the pile is under the left workbench.

**Comment by ghost** [comment]
Couches und Sessel vor dem rechten Spiegel wegräumen, da kommt der Müll hin.

**Comment by ri0t** [comment]
Das geht so nich. Da kommt morgen wie angekündigt das Modularkarussel hin.
