### ISSUE TITLE
Stellwand Mainhall Rolle austauschen

### ISSUE THREAD

**Issue by ghost** [c-base/meta#252]
neue Rolle kaufen & anbauen
Reinigen Aufkleber entfernen

**Comment by uwekamper** [comment]
Die Rollen für die Stellwand mit den vielen Schaltern habe ich mal bei Bauhaus gekauft.

**Comment by ghost** [comment]
kannst du bitte neue besorgen?

**Comment by ghost** [comment]
Heiner hat Ersatzrolle besorgt. Ich (uk) habe sie gerade getauscht. Neue Rolle ist noch nicht abgefahren, daher etwas zu groß - ich lass das jetzt einfach mal so :-)
