### ISSUE TITLE
schwarze Stellwände überstreichen

### ISSUE THREAD

**Issue by ij0n** [c-base/meta#253]
Mit schwarzer wandfarbe. Wenn nötig vor dem streichen reparieren/ausbessern/ spachteln.

**Comment by ij0n** [comment]
Viele sind schon gestrichen, einige mussten erst gespachtelt werden, da dann bitte heute schleifen und überstreichen.

**Comment by dvzrv** [comment]
zwei aus dem soundlab wurden ebenfalls mit acrylspachtel ausgebessert, abgeschliffen und angestrichen.
Alle bis auf zwei in der c-lib stehen nun in der mainhall.

**Comment by ij0n** [comment]
Wie ist der Status der beiden Stellwände in der c-lib? Sind die gestrichen oder nicht?

**Comment by ri0t** [comment]
@dvzrv aah - großartig!

**Comment by dvzrv** [comment]
@ij0n die zwei in der c-lib schienen soweit okay, aber bei einer war noch ausgebessert worden.. da muss man noch mal an ein paar stellen mit schwarz drüber. vll mach ich das später

**Comment by ghost** [comment]
Sind nochmal aufgespachtelt worden. Die linke hat eine riesendelle, wo spachteln keinen sinn ergibt - d.h. fertig.
