### ISSUE TITLE
Connect columns to DMX

### ISSUE THREAD

**Issue by uwekamper** [c-base/meta#254]
The LED lights in the columns can be connected to the DMX light control.

Materials needed:

- DMX-compatible Cable (3-pin, 120 Ohms)
- 8 male XLR-3-pin connectors
- 8 female XLR-3-pin connectors

In every column we need to do the following 
- Check the electronics and make sure that the connections to mains power is not a fire hazard.
- Set the correct address (c-ven set to use addresses vom 0 upward).
- c-ven said the lights will most likely use 5 DMX channels
- test it (how?)

**Comment by uwekamper** [comment]
Plugs have been ordered at reichelt.de

**Comment by uwekamper** [comment]
Sicherung ist Nr. 20 im Sicherungskasten. Die Schalter an der Bar schalten nicht alle Zuleitungen ab.

**Comment by uwekamper** [comment]
LED-Lampen sind von "Eurolight", Kanal 1-3 sind RGB, die restlichen 3 sind für Programme und Effekte (Stropo, Fade etc.) und werden eigentlich nicht benötigt (6 Kanäle insgesamt).

**Comment by ghost** [comment]
blocked by #257

**Comment by ghost** [comment]
First 3 columns now are have DMX cables - you can test them with the mini-DMX controller behind the first column the light next to the windows and stage.

**Comment by uwekamper** [comment]
No, this issue is not blocked by issue #257 .  The cables can work without a cable-canal. The canal must be mounted before Matelight is reerected.

**Comment by uwekamper** [comment]
The XLR plugs will be late, DHL says: "Rücksendung eingeleitet - Die Sendung entspricht nicht den Versandbedingungen."
