### ISSUE TITLE
Kabel für Hüllenintegritäts-Anzeige in der Mainhall mitverlegen.

### ISSUE THREAD

**Issue by uwekamper** [c-base/meta#256]
Es soll ein Kabel zu den Fenstern gelegt werden.
Wenn eines oder mehrere der Mainhall-Fenster geöffnet sind, soll eine Lampe an der Schleuse ausgehen.

Das Prinzip ist das Gleiche wie die Anzeige an der c-lab-Tür.

- [ ] Kabel (c-ven hat mir bereits ne Rolle Kabel gegeben, liegt im CASE

Kabel soll während der Bauwoche mitinstalliert werden, weil wir da eh frische Kabel verlegen.

**Comment by ghost** [comment]
blocked by #257

**Comment by ij0n** [comment]
Missing cable! where is it?
