### ISSUE TITLE
Matelight wieder aufbauen

### ISSUE THREAD

**Issue by ij0n** [c-base/meta#260]
blocked by #254 and #257

**Comment by ij0n** [comment]
erst muss noch die PA aufgebaut werden, das banner ins fenster gehängt werden, der molton davor gehängt werden

**Comment by uwekamper** [comment]
PA und Banner sind inzwischen aufgebaut. Es fehlt noch der Molton.

Vor dem Aufbauen des Matelights bitte auch nochmal mit einer Wasserwage checken, ob die Bühnenelemente jetzt beide gerade stehen und gleich hoch sind.

**Comment by herzmut** [comment]
Matelight aufgebaut.
