### ISSUE TITLE
Fix DMX issues in mainhall

### ISSUE THREAD

**Issue by uwekamper** [c-base/meta#268]
DMX breaks when we send these bytes over artnet:

```
00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|dc|76|0a|dc|76|0b|dc|75|0b|dc|76|0b|dc|76|0a|dc|76|0b|dc|76|0b|dc|76|0b|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00|00
```
It seems like some of the bytes get are shifted (and thus are getting sent to the wrong channels) whenever you hit a color near: RGB(0xdc,0x76,0x0a)

**Comment by uwekamper** [comment]
Links zum verwendeten Code:

- https://code.fe80.eu/lynxis/usbnode
- sowie der openwrt feed (noch mit alten urls) https://github.com/lynxis/lynxis-packages
- https://code.fe80.eu/lynxis/artnet-examples https://code.fe80.eu/lynxis/libartnet

**Comment by uwekamper** [comment]
Es gibt ein Verwaltungssoftware für den ENTTEC USB-to-DMX-Adapter: https://www.enttec.com/eu/products/controls/dmx-usb/pro-manager/ 
Damit kann man u.a. Softwareupdates einspielen und der Windows-PC/Mac kann auch Artnet-Node sein (wir könnten also statt der Dockstar z.B. meinen Mac anschließen)

**Comment by uwekamper** [comment]
USB-DMX-Converter vermutlich dieser hier: https://www.thomann.de/de/enttec_dmx_usb_pro_interface.htm bzw. https://www.enttec.com/eu/products/controls/dmx-usb/dmx-usb-pro/

**Comment by lynxis** [comment]
@uwekamper 
* was passiert denn genau, wenn du das paket verschickst?
* konntest du checken, ob das korrekte paket an den usb enttec geschickt wird?

**Comment by uwekamper** [comment]
Es ist der Wert 0x0A (Dezimal 10), der den Fehler auslöst. Zufälligerweise ist das in ASCII ein Newline :-)

**Comment by uwekamper** [comment]
Gestern ein DMX backend auf einen Raspberry-Pi-3 installiert und statt der Dockstar eingebaut: https://github.com/c-base/dmxbackend

Damit treten die nun nicht mehr auf. Aus dem C-Code ist nicht offensichtlich, warum der Wert 10 ein Problem darstellen sollte.

**Comment by cketti** [comment]
Neues Repo hier: https://github.com/c-base/dmx-gatekeeper

**Comment by uwekamper** [comment]
Ich denke, diese Issue können wir schließen. Wir haben eine Lösungen gefunden.
