### ISSUE TITLE
Kanboard.net für die c-base evaluieren

### ISSUE THREAD

**Issue by uwekamper** [c-base/meta#277]
Open-Source-Variante mit LDAP und Github-Plugin ausprobieren.

https://kanboard.net/

**Comment by uwekamper** [comment]
@woodworker hat es vorgeschlagen.

**Comment by ri0t** [comment]
Bis auf 30 übersetzte Sprachen und die noch zu erledigende LDAP-Auth könnten wir das mit Isomer-Project machen. Eine Instanz auf HVA gibt es schon, ich kümmere mich mal zeitnah um LDAP. Fehlt evtl. noch die 'öffentliche' Erreichbarkeit (also vong internet her)..
