### ISSUE TITLE
Elektronik an Spaceshlongs anschliessen und im Weltenbaulab aufhaengen

### ISSUE THREAD

**Issue by coon42** [c-base/meta#280]
Ich habe alle Shlongs abgebaut und im c-lab deponiert. Dort werde ich nun nach und nach die fehlenden Stecker an die Shlongs loeten und an die Platinen anschliessen (Und diese gleichzeitig Testen). Nach meinem Kenntnisstand fehlt nur noch eine Platine fuer die Ansteuerung aber die kann schnell am Ende geloetet werden.

**Comment by cascha42** [comment]
ich schliesse das mal.

yipyip.
