### ISSUE TITLE
c-crawl!

### ISSUE THREAD

**Issue by ri0t** [c-base/meta#291]
We (@ri0t & @fuzxxl) are in the process of setting up a crawl online server for c-members.

* [ ] Get the daemon working on FreeBSD
* [ ] Get highscore pages working ( https://github.com/crawl/scoring )
* [ ] Advertize among members
* [ ] Organize a tournament (Maybe even use https://github.com/crawl/dcss_tourney ??)

**Comment by uwekamper** [comment]
Seit 3 jahren nix passiert. Ich schließe das jetzt erstmal.
