### ISSUE TITLE
Lager zugänglich machen

### ISSUE THREAD

**Issue by ligi** [c-base/meta#307]
Lager (vor werstatt) ist vollgestellt - sollte wieder zugänglich gemacht werden

**Comment by ij0n** [comment]
Wie immer sammelt sich der Müll für eine BSR Tour vorm Lager. Kann größtenteils alles weg

**Comment by Kaosstern** [comment]
Habe Optimierungsmaßnahmen durchgeführt.
- Bevor der Tisch weggeworfen wird, bitte die Rollen abschrauben !

**Comment by ij0n** [comment]
Ist wieder ziemlich zugänglich, Dank der Migration des Tisches in das c-lab
