### ISSUE TITLE
NEC monitor am stehtsch installieren

### ISSUE THREAD

**Issue by ligi** [c-base/meta#313]

**Comment by ij0n** [comment]
Welcher Stehtisch wo?

**Comment by ligi** [comment]
Der wo die spiele dunter sind

**Comment by ij0n** [comment]
Ich halte den NEC für deutlich viel zu groß für diesen ort

**Comment by ligi** [comment]
Meinst du strukturell oder optisch?

**Comment by uwekamper** [comment]
Kein NEC mehr übrig, alle verbaut in der mainhall oder bei EVAs kaputt gegangen.
