### ISSUE TITLE
Beamer für einen Issue-Tracker

### ISSUE THREAD

**Issue by bengoshii** [c-base/meta#316]
Der Issue-Tracker soll während der Bauwoche über den Beamer in der Nerdarea wiedergegeben werden. Großartig wäre aber eine dauerhafte Konstruktion, so dass jeder, der sich in der Station einbringen kann, gleich sieht, was anliegt. Und für alle anderen wäre es ein Mahnmal.

**Comment by Kaosstern** [comment]
Hab temporär meinen laptop hin gestellt und den issue-tracker eingeblendet
