### ISSUE TITLE
Bar - Grundreinigung

### ISSUE THREAD

**Issue by bengoshii** [c-base/meta#322]
Einmal wirklich alles von, um über und unter der Bar ausräumen, reinigen, und wieder einräumen oder entsorgen. Bei der Gelegenheit Kabel sauber verlegen.

**Comment by ri0t** [comment]
Oberes Deck wurde entrümpelt und gereinigt. Muss wieder einsortiert (und ggf. nochmal müll rausfischen) werden. Unterdeck ist vmtl. noch ungereinigt.

Das mini-putzkabuff am eingang könnte auch noch etwas liebe vertragen.
