### ISSUE TITLE
Stationsmodell aufhängen

### ISSUE THREAD

**Issue by bengoshii** [c-base/meta#325]
Es gibt einen Drehmotor und einen Platz - über der Wendeltreppe - aber aufgrund der Höhe muss ein kleines Gerüst oder ähnliches aufgebaut werden, um da ranzukommen. Das macht sich alleine auch nicht gut. Teile sind alle da - es muss "nur" angebracht werden.

**Comment by ij0n** [comment]
Here is an idea how to get to the mounting point

![threema-20220621-120631106](https://user-images.githubusercontent.com/4204566/174780826-5329d074-92c6-4019-aa2b-a51cf03e7706.jpg)
