### ISSUE TITLE
Schleusenrechner broken

### ISSUE THREAD

**Issue by bengoshii** [c-base/meta#327]
Der Schleusenrechner hängt sich regelämäßig auf und ist nur durch einen Neustart zum Leben zu erwecken.

Ferner ist ein Monitor grünstichig.

**Comment by berlincount** [comment]
![DD598017-51AF-4A3A-BE7D-D090CD888C32](https://user-images.githubusercontent.com/545500/76164333-69e24000-614e-11ea-9165-390c8552e169.jpeg)

![572662A8-EB2D-4D9E-99C0-70B23D84C802](https://user-images.githubusercontent.com/545500/76164367-9ac27500-614e-11ea-82d4-18f95b982248.jpeg)

Hab ich nicht demontiert bekommen ☹️

**Comment by berlincount** [comment]
@cmile hmm, der Rechner crasht scheinbar wenn man da was am DVI macht?

Wär‘s sinnvoll wenn man den Rechner mal durch 'nen Raspberry Pi 4B mit zwei HDMI-auf-DVI-Adaptern austauscht?
