### ISSUE TITLE
Treppenlaufrichtung markieren

### ISSUE THREAD

**Issue by ri0t** [c-base/meta#330]
Der Bordcomputer flüsterte: Die Treppe ist wohl ein britisches Modell und eher für den Linksverkehr gedacht. Von oben herab machen das eh alle automatisch, aber von unten herauf nicht.
Daher sollten die Treppen von unten herauf von vorne Richtungspfeile bekommen.

**Comment by ligi** [comment]
top idee!-)

**Comment by bengoshii** [comment]
Vielleicht könnten wir unsere Ampeln dafür auch sinnvoll einsetzen - wird die Treppe auf einer Seite betreten, wird es unten grün und oben rot oder entsprechend umgekehrt

**Comment by uwekamper** [comment]
wontfix
