### ISSUE TITLE
Geraffel vor Spiegel/HE2 entfernen

### ISSUE THREAD

**Issue by ri0t** [c-base/meta#335]
Vieles davon wird hoffentlich während der Bauwoche montiert oder weggeräumt (u.a. versch. Nec-Displays).

Sieht aber momentan eher aus wie eine versteckte Müllecke.

**Comment by ligi** [comment]
possible duplicate of #190

**Comment by ri0t** [comment]
> possible duplicate of #190

Hm. Nah, damals hatten wir sie kurzzeitig frei. Da wurde wieder reingekramt :D
Anyway. Ich update dann den zombie mal.
