### ISSUE TITLE
Robolab Arbeitsplätze umstellen

### ISSUE THREAD

**Issue by c-haosle** [c-base/meta#338]
- Existierende Arbeitsplätze auf Circle Beschluss respektierende Arbeitspläte umbauen (einsehbar) 
- zusätzliche Circle Beschluss respektierende Arbeitspläte aufbauen (einsehbar)

**Comment by Kaosstern** [comment]
Der circle Beschluss ist mir unbekannt.
Zu welchem circle wurde das bitte beschlossen?

**Comment by c-haosle** [comment]
k.a. habe ich so aufgeschnappt....
