### ISSUE TITLE
Robolab klappbaren Arbeits und Spiele Tisch evaluieren

### ISSUE THREAD

**Issue by c-haosle** [c-base/meta#339]
Robolab klappbaren Arbeits und Spiele Tisch evaluieren
UND falls machbar umsetzen !!

**Comment by Kaosstern** [comment]
Die evaluation wurde bereits vor geraumer zeit von mir durch geführt.
Durchführbarkeit ist gegeben. Einzig die Implikationen sind ab zu wägen...
( primär die (vernachlässigbare) Verminderung der strukturellen integrität des Tisches nach den notwendigen modifikationen )
