### ISSUE TITLE
Robolab Biolab Ecke einrichten

### ISSUE THREAD

**Issue by c-haosle** [c-base/meta#340]
Für den Biolab workshop (KW14) den Technik demonstrator aufbauen bzw. vorbereiten.

- ~~Platz freiräumen~~
- ~~Rahmen bauen~~
- bewässerung bauen
- beleuchtung bauen
- monitoring bauen

**Comment by bengoshii** [comment]
Du willst in einem vollgerauchten Raum ein Biolab einrichten? Ist das nicht Pflanzenquälerei?

**Comment by c-haosle** [comment]
> Du willst in einem vollgerauchten Raum ein Biolab einrichten? Ist das nicht Pflanzenquälerei?

Es geht darum, Darvinismus zu beweisen ... nur das stärkste Gewächs wird überleben/sich durchsetzen ... wenn nichts überlebt ... dann ist da einfach die biosphere kaputt und wahrscheinlich auch für C-Einkeiten nicht empfehlenswert
