### ISSUE TITLE
Neue Bänke für die Außentreppe

### ISSUE THREAD

**Issue by uwekamper** [c-base/meta#35]
Wir haben auf der Treppe am Hintereingang der c-base Bänke mit den Plastik-Sitzschalen auf Sperrholz. Das Sperrholz ist langsam durchgefault und einige der Dinger sind auch schon kaputtgebrochen.

Ich würde gerne eine Konstruktion wie auf der Republica 14, wie sie hier im Bild zu sehen ist, haben:

![](http://i1.ytimg.com/vi/TgAdXibXgMk/0.jpg)

Eine einfache Holzplatte auf einem Euro-Behälter/Bäckerkiste. Ist sehr einfach herzustellen, evtl. nicht unbedingt die billigste Lösung.

Quelle für Eurokisten: http://www.auer-packaging.de/de/b-ware_38-1.html

**Comment by ij0n** [comment]
existiern die plastikschalensitze überhaupt noch? hab die lange nicht mehr gesehen... issue kann zu, oder?
