### ISSUE TITLE
Klingel in der Nerdarea

### ISSUE THREAD

**Issue by luxzeitlos** [c-base/meta#355]
& Alarm wenn die Tür zum Nichtraucherbereich länger offen ist

**Comment by luxzeitlos** [comment]
@uwekamper hat ein Kabelfinder

**Comment by uwekamper** [comment]
In der Nerdarea hängt jetzt eine Klingel (Danke, FUZ).

Ein Kabel ist auch von der Tür in die Nerdarea verlegt. 

Die Klingel in der Nerd ist aber leider noch zu leise.

**Comment by uwekamper** [comment]
Das Kabel muss noch vernünftig zusammengelötet werden.

**Comment by cmile** [comment]
Wir brauchen noch eine lautere Klingel...

**Comment by uwekamper** [comment]
Nachdem ich die Kabel richtig verlötet habe, denke ich, dass die Klingel etwas lauter geworden ist. Ich denke wir können dieses Ticket schließen. 

Für das Projekt "Lautere Klinger in der Nerd" bitte ein neues Ticket aufmachen @cmile .
