### ISSUE TITLE
Asterisk Telefonserver 

### ISSUE THREAD

**Issue by AnsgarSchmidt** [c-base/meta#36]
Einen Asterisk SIP Server installieren mit conference bridge und Zugang uebers Internet. $Member bekomt account und ist neben XMPP auch per SIP erreichbar. StationsCom.

**Comment by jaseg** [comment]
Status? Das Issue ist bald ein Jahr alt, und bei mangeldem Interesse würd ich es dann einfach mal zu machen.

**Comment by cmile** [comment]
freeswitch läuft seit mehreren jahren und kann wie @jaseg sagt auch so ziemlich alles, was asterisk kann nur mit weniger schmerz. wenn irgendwas am freeswitch verbessert/verändert werden soll, möge ein neues issue aufgemacht werden
