### ISSUE TITLE
Bestell-o-matic fertig bauen fuer c-lab

### ISSUE THREAD

**Issue by AnsgarSchmidt** [c-base/meta#38]
Interner Webservice um Sammelbstellungen (reichelt, china, pizza) zu verwalten. Idee und Anfangscode von @XenGi. Bestellung starten, Enddatum festlegen, Sammelbestellung nach $Shop exportieren, einzelnen $Rechnungen erzeugen.

**Comment by jaseg** [comment]
Falls sich da doch noch was tut, bitte einfach wieder aufmachen. Momentan erfüllen IRC und Mailman diese Aufgabe ja ganz gut.
