### ISSUE TITLE
Die Kellerfenster im Weltenbaulab sind voll die Katastrophe

### ISSUE THREAD

**Issue by uwekamper** [c-base/meta#39]
- Gehen nicht auf, die Kurbel dreht sich nicht oder macht nix
- Wenn sie offen sind, gehts doof wieder zu
- Einfach mal selbst versuchen, dann versteht ihr schon, was ich meine.

**Comment by uwekamper** [comment]
Ist immer noch so.

**Comment by XenGi** [comment]
Hat der @berlincount da mal was gemacht?

**Comment by berlincount** [comment]
Nope.

**Comment by ligi** [comment]
Da gibts Fenster? Hab die nie als solche gesehen - schau ich mir an wenn ich wegen #231 dort bin. Kurbel geht nicht klingt von der Ferne erstmal nach WD-40 - aber wenns nur das währ dann hätt @uwekamper glaub ich den issue nicht aufgemacht ..

**Comment by berlincount** [comment]
Die Wohnwerkstatt hat einen Auftrag an die entsprechende Tischlerei gegeben, wir kriegen motorisierte Fenster mit Fernbedienung.
