### ISSUE TITLE
Zahnarztstuhl aus der c-lib auslagern

### ISSUE THREAD

**Issue by uwekamper** [c-base/meta#43]
Der steht da im Weg rum und ist sackeschwer. Brauchen wir den noch?

**Comment by ij0n** [comment]
wohnt jetzt erstmal unter der treppe. is da weniger im weg, sieht aber immer noch dekorativ aus.

**Comment by hellm00d** [comment]
Ich kümmere mich gerade um die Abholung.
Werde mich dabei der c-base um +10m nähern aber nicht betreten.

m00d

Am 11.10.2015 um 14:51 schrieb ijon <notifications@github.com>:

**Comment by hellm00d** [comment]
erzähl mal mehr..

wohin solls? wer will das ding haben?
