### ISSUE TITLE
secunda:rantenne

### ISSUE THREAD

**Issue by woodworker** [c-base/meta#51]
c4os und ich habe pla:ne in siri gefunden, das es an board der c-base wohl auch immer noch sogenante secunda:rantennen gab, diese c_einen wohl im maCtab irgend was cwic_en 1:100 (368cm) und 1:200 (184cm) cur hauptantenne gewesen sein.

wir mu:Cen so min. eine secunda:rantenne unbedingt an board rendern um in mo:glichen angriffCcenarien auf die hauptantenne nicht den interstelaren func verlieren

**Comment by ij0n** [comment]
Projekt abgeschlossen. Maßstab 1:42. Erstinstallation auf dem Camp15.
