### ISSUE TITLE
eCen faCen

### ISSUE THREAD

**Issue by woodworker** [c-base/meta#52]
Lieferanten hinzufuegen
- Name
- Telefon
- Internet Addresse
- Unsere Kundennummer

Bestellung starten
- #pizza support?
- Lieferant festlegen oder mini Poll welcher lieferant gewuenscht ist
- Endzeit der Essensbestellung / Bis wann können bestellungen abgegeben werden
- Einzelitems können hinzugefgt werden
- Preistracking
- Abhakliste wer schon bezahlt hat
- Bestellung als rausgeschickt markieren
- Bestellung als angekommen markieren
  - Mail / Jabber message / was auch immer an die mitbesteller schicken
- Bestellung als vollständig markieren
- Bestellungen können von den bestellern mit lecker von 1-5 bewertet werden
- Lieferanten Lieferzeit mittracken und nach Tag und Uhrzeit der Bestellung aufschluesselbar machen

Stuff
- Mobile friendly liste zum abhaken
- REST API
- c-beam anbindung

Weitere Ideen
- Info Display fuer die Bar das Bestellungen ankommen / angekommen sind
- Real World Display zum anzeigen das bestellungen aktiv sind?
- Bekantgabe ueber c_out?

Wer weitere Interessante Ideen hat hier posten oder per mail an mich
woodworker@c-b.o

**Comment by ij0n** [comment]
Wontfix
