### ISSUE TITLE
Beleuchtung Ceminarraum

### ISSUE THREAD

**Issue by e-punc** [c-base/meta#55]
der Raum braucht dringend neues Licht.
Einmal was gemütliches zum arbeiten.
Gibt wohl schon ein Halogen-Seil-System, das da rumliegt.

Ich fänd auch eine Stange schick, an die man ein Paar Baustrahler hängen kann um den Greenscreen zu nutzen.

**Comment by ij0n** [comment]
Halogen Seil System ist zwischenzeitlich installiert worden.
