### ISSUE TITLE
Microcontroller-Zoo

### ISSUE THREAD

**Issue by uwekamper** [c-base/meta#60]
Wir haben nun eine Kiste im c-lab mit so ungefähr 10 Controllern
Diverse ATMega, ATTiny, MSP430 und ARM basierte Boards auch mit LAN und WLAN

Analog zum "Open Device Lab" und dem c-base Mobile Device-Zoo sollen die Boards zum Ausleihen zur Verfügung stehen.

**Comment by silps** [comment]
muss ich was anmelden wenn ich was ausleihe ?
habe den avr dragon genommen und arbeite damit im robolab ^_^

**Comment by XenGi** [comment]
Einfach irgendwann wieder zurück bringen.
