### ISSUE TITLE
Beleuchtung T-Shirt Demokabinett

### ISSUE THREAD

**Issue by ri0t** [c-base/meta#63]
Needs new light.
@XenGi schlug vor, einfach nen haufen (10 reichen sicher) weiße LEDs passend verwiderstandet  an einen glühwürfel zu hängen. :+1:

**Comment by ghost** [comment]
uk und electronicego haben eine blaue LED-Leiste installiert als Ersatz für die Kaltlichtkathoden

**Comment by ghost** [comment]
LED-Strahler wurden gekauft, müssen noch montiert werden

**Comment by ij0n** [comment]
sind montiert! sieht geil aus! thx to ego and derek (alien)
