### ISSUE TITLE
Barstatus-Indikator im c-lab reparieren

### ISSUE THREAD

**Issue by uwekamper** [c-base/meta#68]
Ich habe versucht, die falschen Farben am Barstatus-Indikator im c-lab zu korrigieren. Es ist aber kein Hardware-Fehler, sondern vermutlich ein Software-Bug. Ich hatte angekommen, dass nur zwei der drei Farb-Leitungen vertauscht waren. Das war aber nicht der Fall. Es leuchten zwei der drei Farben gleichzeitig. Das deutet darauf hin, dass die Software die falschen Werte ausgibt.

**Comment by cmile** [comment]
wie sich herausstellt, handelt es sich nicht um einen hardwaredefekt, sondern um ein zeichen des widerstands gegen der kapitalistische verwertungslogik der c-lab-bewohner
