### ISSUE TITLE
Update alien alarm

### ISSUE THREAD

**Issue by silps** [c-base/meta#7]
connect alien alarm to c-mote/c-beam

**Comment by bergie** [comment]
If we have the alien alarm coming to c-beam (MQTT), it should also be represented as [a participant](https://github.com/c-base/c-flo/tree/master/participants) on c-flo so it can be connected to arbitrary systems

**Comment by bergie** [comment]
we have a little animation we could trigger in downstairs info screens if we had alien alarms on MQTT http://c-flo.cbrp3.c-base.org/alien-alarm/

**Comment by ij0n** [comment]
which is the closest MQTT-enabled device with a free io-pin? Afaik in the c-info sign there is something. can we use that?

**Comment by ij0n** [comment]
Now thinking about it - if we have to touch the hardware of the c-info sign to do something with it regarding alien-alarm-button, then we should check issues #93 and #94 
and evaluate what solution is best to combine all these issues in one soution.

**Comment by cascha42** [comment]
the door is on the network, and publishes the door and alien alarm status to mqtt.
im replacing the sound-module at some point, cause it hangs up sometimes

cascha

**Comment by cascha42** [comment]
#287 good news: sound-module fully fixed!

a push on the button, or closings /  openings of the door affects a message to the MQTT on Topic "alien-alarm"

Source-Code for MQTT Connection: https://github.com/c-base/c-flo/tree/master/devices/alien-alarm

closing..
cascha
