### ISSUE TITLE
[Bookscanner] Umlenkrollen austauschen gegen Neuteil

### ISSUE THREAD

**Issue by ij0n** [c-base/meta#73]
![2014-12-05 23 22 07](https://cloud.githubusercontent.com/assets/4204566/5324736/c0569756-7cde-11e4-88e4-c19b9bc5b381.jpg)

So siehts derzeit aus. Die Metallteile müssen raus und ausgetauscht werden gegen die neuen. Die neuen sind fertig und sehen so aus: 

![2014-12-05 23 22 30](https://cloud.githubusercontent.com/assets/4204566/5324729/aae4ffca-7cde-11e4-8eda-cf83cf744e2a.jpg)

Danke an Tintan für die Herstellung der Teile!

Als Kraftübertraung soll keine Kette mehr dienen, sondern ein mehrfach umgenähter Streifen Stoff. Das ist leiser, weicher und angenehmer. Die vertikalen Ständer sind nicht tief genug für beide Lager, müssen also oben durch Anbau eines Holzteils etwas breiter gemacht werden, so dass Sie tiefer reichen.

**Comment by samthetechie** [comment]
this translates (google translate) as: "Replace [Book Scanner] pulleys with a new one # 73" 

So currently the metal parts have to get out and replaced with the new one. The new finish and look like this:

Thanks to Tintan for the manufacture of the parts!
As Kraftübertraung should serve no more chain, but a multiple re-sewn fabric strips. This is quieter, smoother and more enjoyable. The vertical uprights are not deep enough for both camps, must therefore be made slightly wider at the top by mounting a piece of wood, so you go deeper.

**Comment by samthetechie** [comment]
Some other solutions for book scanner pulleys: http://www.instructables.com/id/Book-Scanners/step13/Pulleys/

**Comment by ij0n** [comment]
yep. is done.

sehr leise und ruhig!
