### ISSUE TITLE
Aquarium fürs Matelight

### ISSUE THREAD

**Issue by uwekamper** [c-base/meta#78]

**Comment by uwekamper** [comment]
Pixelfische FTW

**Comment by XenGi** [comment]
Kannste in pymlgame bauen. Ich helf dir wenn du willst.

**Comment by jaseg** [comment]
Als .gif würde es auch reichen.

**Comment by uwekamper** [comment]
gibt es jetzt, wir haben ein aquarium-video von youtube geladen und als MP4 abgespeichert. Kann per Mateplay.sh auf dem Matelight abgespielt werden.
