### ISSUE TITLE
Fahrende Laufschrift: Matelight auf einem Zug

### ISSUE THREAD

**Issue by uwekamper** [c-base/meta#80]

**Comment by XenGi** [comment]
Nach hackers on a plane jetzt Matelight on a train!

**Comment by uwekamper** [comment]
Weitere Idee: Laufschrift mit der Geschwindigkeit des Zuges so synchronisieren, dass es aussieht, also ob die Schrift steht.

**Comment by jaseg** [comment]
Ich mach das hier mal zu, da wir das höchstwahrscheinlich aus Kippstabilitätsgründen absagen müssen.
