### ISSUE TITLE
Non-food-Automat

### ISSUE THREAD

**Issue by uwekamper** [c-base/meta#81]
mit Dingen befüllt, die man spät nachts, wenn die Läden zu sind, gebrauchen könnte. z.B. Micro-USB-Ladegeräte, Arduinos, MOSFETs, div. andere Kleinteile.

**Comment by ij0n** [comment]
solche Geräte: http://www.ebay.de/itm/AUTOMATIC-PRODUCTS-SNACKSHOP-121C-SNACKAUTOMAT-SPIRALAUTOMAT-DESIGN-2-/321687317636?pt=LH_DefaultDomain_77&hash=item4ae60eec84 kosten auf ebay von 1000€ bis 5000€

Interessante Idee! Bezahlt sich so ein Automat selbst?

**Comment by berlincount** [comment]
in Anbetracht der notwendigen Wartung, der Kapitalbindung durch Bestückung, der Gemeinnützigkeit, der nur bedingten Gewinnerzielungsabsicht, der vermutlich eher moderaten Nutzung, der schnellen (Über)Alterung des Inhalts: eher unwahrscheinlich.

**Comment by ij0n** [comment]
wontfix. closed.
