### ISSUE TITLE
gelben Replicator in Betrieb nehmen

### ISSUE THREAD

**Issue by ij0n** [c-base/meta#82]
Elektronik raus und neu bauen (johns pläne) oder Elektronik durch nen Raspberrypi und nen paar atmels ersetzen (tintans vorschlag) und gerät in betrieb nehmen

automatische verladung auf monorails berücksichtigen beim aufstellort.

**Comment by woodworker** [comment]
bitte auch bedenken das evtl. liefer drohnen vom BER kommen könnten

**Comment by XenGi** [comment]
Nicht zu vergessen die Anbindung an die Seidenstraße!

**Comment by cascha42** [comment]
MM war fleißig!
Ich schließe das Mal.

ps. Error 404: monorail network not found.
