### ISSUE TITLE
Automatic index of pads on pad.c-base.org

### ISSUE THREAD

**Issue by berlincount** [c-base/meta#83]

**Comment by ij0n** [comment]
@ri0t hattest du da nicht mal was gebaut für den hackerfleet-padserver?

**Comment by ri0t** [comment]
ist jahre her und hat per grep ein sqlite system durchforstet - furchtbar ineffizient und mit mysql und/oder nem viel benutzen pad das nicht regelmässig gecleared wird (was auch doof ist) nicht vernünftig machbar

**Comment by ri0t** [comment]
Obsolet durch codi-md.

_Widersprich mir._
