### ISSUE TITLE
Elektronik für LED-stripes in der c-info-wand

### ISSUE THREAD

**Issue by cmile** [c-base/meta#85]
jemand müsste mal die elektronic für die LED-stripes zusammentüddeln. zugriff auf die LED-stripes durch entfernen der schrauben an der oberen abdeckung

MOSFETs liegen im c-lab in der open-step-kiste

**Comment by cmile** [comment]
uk und ich haben enthubelt.

hinter dem c-info schild befindet sich ein connected launchpad, USB-kabel und ethernet kabel liegen oben auf der nerdctrl-schalterwand.

TODO: 
- 3-fach-steckdose hinter das c-info schild bauen
- lichtsteuerung verbessern
- mqtt anbindung
- einen hardware-button zur steuerung anbauen

**Comment by XenGi** [comment]
Der USB-Strom kann gerne wieder ins c-lab. Ich tausche das bei Gelegenheit gegen einen entbärlichen USB-Stöpsel aus.
