### ISSUE TITLE
Temperatursensor am Grill

### ISSUE THREAD

**Issue by ij0n** [c-base/meta#89]
Wir benötigen einen Temperatursensor am Grill, damit wir feststellen können, ob dieser gerade heiss ist. 

Gibt mehrere technische Optionen...es liegt aber nicht an mir das zu entscheiden. 

Stromversorgung
a) Kühlkörper und diese Metalldinger die bei ausreichend temperaturdifferenz strom produzieren?
b) Akku und Solar
c) Kabel
Datenübertragung
a) Kabel
b) Funk
b1) Wifi
b2) Zigbee/NRF...

Ziel der Angelegenheit ist, dass c-beam weiss, ob der Grill an ist. Cool wäre auch eine uptime vom grill :-D

**Comment by jaseg** [comment]
Diese Dinger heißen Peltierelemente, und sind aus Silizium und daher nicht hinreichend hitzefest. Ich wäre für eine Lithiumbatterie, damit kann man 'nen nrf24l01+ in diesem anwendungsfall etwa ein jahrzehnt betreiben. nrf24l01 ist hier definitiv die schnellste und einfachste lösung.

**Comment by jaseg** [comment]
Als Temperatursensor kommt hier eigenlich nur ein PT100 infrage, da alles andere bei den Temperaturen aussteigen wird. PT100 bekommt man auch mit schick paarhundertgrad temperaturfester Zuleitung+Gehäuse.

**Comment by ij0n** [comment]
wollen wir nicht lieber nen datenkabel fest rauslegen und da z.b. wettersensorik, tageslichtwarn-sensoren und den grill mit anklemmen?

**Comment by jaseg** [comment]
Langfristig ja, kurzfristig nein.

**Comment by berlincount** [comment]
Infrarot-Kamera durch's Fenster? ;) Wenn Datenkabel, dann bitte PoE, und eher null Festinstallationen schon garnicht 'am Zaun des Nachbarn', der ist uns im wesentlichen nicht freundlich gesinnt ..

**Comment by jaseg** [comment]
bimetall klingt gut, schalter und zuleitungen müssen jedoch bis ein paarhundert grad temperaturfest sein und auch spritzwasser/-fett aushalten können.

**Comment by jaseg** [comment]
Ich korregiere mich, wir wollen ein Thermocouple, die bekommt man ohne weiteres bis 1200C Messbereich:
 * http://www.aliexpress.com/item/2M-EGT-K-Type-Thermocouple-Exhaust-Probe-High-Temperature-Sensors-Threads-New-BS-High-Quality/32227681517.html
 * http://www.aliexpress.com/item/New-For-Stainless-Steel-High-Temperature-100-To-1250-Degree-Thermocouple-K-type-100mm-Probe-Sensors/2001511122.html

**Comment by jaseg** [comment]
1800C: http://www.aliexpress.com/item/Free-shipping-3pcs-lot-Ceramic-thermocouple-B-type-thermocouple-3pcs-lot/373564252.html

**Comment by jaseg** [comment]
Also, einer oberflächlichen Recherche zufolge sollte ein 1200C-Thermocouple zur Messung der Gluttemperatur geradeso ausreichen. Mit 1500C oder so sind wir in jedem Fall auf der sicheren Seite, da irgendwo dort der Schmelzpunkt des Grills liegen sollte.

**Comment by jaseg** [comment]
Hat hieran noch irgendjemand Interesse? Ich stehe gern mit Rat und beschränkten Mengen Tat zur Seite, hab aber selbst keine Zeit dafür. Falls sich keiner meldet, mach ich dieses Issue nämlich zu.

**Comment by jaseg** [comment]
Hab gestern mal eine schnelle Kalkulation gemacht:

MAX31855 für 5eur plus http://www.aliexpress.com/item/2M-EGT-K-Type-Thermocouple-Exhaust-Probe-High-Temperature-Sensors-Threads-New-BS-High-Quality/32227681517.html abgas-thermocouple bis 1200C für 10eur. Plus Gehäuse und so insgesamt vmtl. um 50eur. Ijon fand das zu teuer.

**Comment by ri0t** [comment]
Aah, fsck it. Nen sensor ist überkandidelt und wie da oben steht, zu teuer. Ich mach lieber ein neues Ticket auf. Wir brauchen einfach nen statusinterface zum aktivieren des grillstatus.
