### ISSUE TITLE
3-fach-steckdose hinter das c-info schild bauen

### ISSUE THREAD

**Issue by cmile** [c-base/meta#91]
zur stromversorgung des c-info schildes müsste noch jemand eine ordentlich verlegte 3-fach-steckdose hinter das c-info schild (oben) bauen

**Comment by ij0n** [comment]
warum? was muss da oben noch so dran? wäre eine verkabelung mit wago-klemmen und aderendhülsen nicht sinnvoller?

**Comment by cmile** [comment]
momentan brauchen wir da drin 2 stecker, ein 12V netzteil für die streifen und ein USB netzteil für das launchpad.

alternativ könnte man netzteil einbauen, dass 5V und 12V liefert und da einen micro-USB-stecker drandengeln

**Comment by uwekamper** [comment]
Das doppelte 5V-USB-Netzteil, dass zur Zeit da dran ist, soll bitte zurück ins c-lab. Wir müssen Zeitnah ein anderes für die c-info-wand besorgen.

**Comment by uwekamper** [comment]
Anderes USB-Netzteil hat sich reingerendert.
