### ISSUE TITLE
launchpad in c-info-wand an mqtt anbinden

### ISSUE THREAD

**Issue by cmile** [c-base/meta#92]
mann müsste mal das connected launchpad in der c-info-wand an c-beam via mqtt anbinden

**Comment by uwekamper** [comment]
http://energia.nu/creating-an-iot-connected-sensor-with-energia-mqtt/

**Comment by ij0n** [comment]
hat es schon nen netzwerkkabel das zum nächsten switch geht?

**Comment by uwekamper** [comment]
Es geht ein Netzwerkkabel raus, aber es geht noch nicht in einen Switch.

**Comment by uwekamper** [comment]
Launchpad ist am MQTT, Sourcecode siehe Wiki oder https://gist.github.com/uwekamper/ebefbdc992248407a1e7
