### ISSUE TITLE
c-base-schild neu verkabeln

### ISSUE THREAD

**Issue by cmile** [c-base/meta#95]
leider sind einige der LED-stripes im c-base-schild neben nerdctrl nicht an die PWM-pins des connected launchpads angeschlossen. zudem ist das ganze konstrukt schlecht wartbar, da die LED-stripes direkt an die lochrasterplatine angelötet sind. beim c funktioniert zu allem überfluss grün nicht.

jemand müsste mal die verkabelung neu machen! am besten mit schicken steckern für die stripes und mit IRL540N MOSFETs

**Comment by uwekamper** [comment]
Das ist AFAIK fertig, oder? @cmile
