### ISSUE TITLE
ansteuerung für spaceshlong

### ISSUE THREAD

**Issue by cmile** [c-base/meta#97]
man müsste mal die elektronik für den spaceshlong bauen

**Comment by ij0n** [comment]
bei der aufhängung der nerdarea-ampel haben cmile und uk großartiger weise bereits strom zum vorgesehenen gehäuse für die elektronik für die spaceshlongs im flur gelegt. dort in der nähe (<0,5m) liegt jetzt ne mehrfachsteckdose hinter der verkleidung.

**Comment by ri0t** [comment]
Siehe auch #173

**Comment by coon42** [comment]
shlong issues zu einem zusammengefasst. Siehe: https://github.com/c-base/meta/issues/280
